services:
  mongodb-exporter:
    image: percona/mongodb_exporter:0.40.0
    container_name: mongodb-exporter
    restart: unless-stopped
    networks:
      - reviews-network
      - shared_ecommerce_network
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    command:
      - '--collect-all'

  app:
    networks:
      - reviews-network
      - shared_ecommerce_network
    image: wesley00s/product-reviews:latest
    container_name: reviews-app
    ports:
      - "8081:8081"
    build:
      context: .
    env_file:
      - .env

networks:
  reviews-network:
    driver: bridge
  shared_ecommerce_network:
    external: true