services:
  mongodb:
    networks:
      - reviews-network
      - shared_ecommerce_network
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongodb-exporter:
    image: bitnamisecure/mongodb-exporter:latest
    container_name: mongodb-exporter
    restart: unless-stopped
    networks:
      - reviews-network
      - shared_ecommerce_network
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

  rabbitmq:
    networks:
      - reviews-network
      - shared_ecommerce_network
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    env_file:
      - .env
    environment:
      - RABBITMQ_PLUGINS=[rabbitmq_prometheus_plugin].
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - mongodb

  app:
    networks:
      - reviews-network
      - shared_ecommerce_network
    image: reviews-image:latest
    container_name: reviews
    ports:
      - "8081:8081"
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq

networks:
  reviews-network:
    driver: bridge
  shared_ecommerce_network:
    external: true