jwt:
  key:
    private:
      path: classpath:certs/private_key.pem
    public:
      path: classpath:certs/public_key.pem
app:
  issuer: ${ISSUER}

spring:
  application:
    name: ProductsReview

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC

  data:
    mongodb:
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      auto-index-creation: ${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION}
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8081
  servlet:
    context-path: /reviews/api
    session:
      timeout: 30m

springdoc:
  swagger-ui:
    path: /docs